services:
  - type: web
    name: zero-touch-qa
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: zero-touch-qa-db
          property: connectionString
      - key: PSI_API_KEY
        sync: false
      - key: WRIKE_API_TOKEN
        sync: false
      - key: WRIKE_CF_SITE_URL
        sync: false
      - key: WRIKE_CF_PARTNER
        sync: false
      - key: WRIKE_CF_PHASE
        sync: false

databases:
  - name: zero-touch-qa-db
    plan: free
    databaseName: zero_touch_qa
    user: ztqa_user
